In [3]:
import requests
from lakehouse.daft import bronze
import json
import daft
from deltalake.table import TableMerger, DeltaTable

In [4]:
CATALOG = "daft_catalog"

# 1. Set Up and Data

In [5]:
res = []
resource = "planets"
query = f"https://swapi.tech/api/{resource}"
json_request = requests.get(query).json()
res.extend(json_request["results"])

while json_request["next"]:
    json_request = requests.get(json_request["next"]).json()
    res.extend(json_request["results"])

In [6]:
res

[{'uid': '1',
  'name': 'Tatooine',
  'url': 'https://www.swapi.tech/api/planets/1'},
 {'uid': '2',
  'name': 'Alderaan',
  'url': 'https://www.swapi.tech/api/planets/2'},
 {'uid': '3',
  'name': 'Yavin IV',
  'url': 'https://www.swapi.tech/api/planets/3'},
 {'uid': '4', 'name': 'Hoth', 'url': 'https://www.swapi.tech/api/planets/4'},
 {'uid': '5',
  'name': 'Dagobah',
  'url': 'https://www.swapi.tech/api/planets/5'},
 {'uid': '6', 'name': 'Bespin', 'url': 'https://www.swapi.tech/api/planets/6'},
 {'uid': '7', 'name': 'Endor', 'url': 'https://www.swapi.tech/api/planets/7'},
 {'uid': '8', 'name': 'Naboo', 'url': 'https://www.swapi.tech/api/planets/8'},
 {'uid': '9',
  'name': 'Coruscant',
  'url': 'https://www.swapi.tech/api/planets/9'},
 {'uid': '10',
  'name': 'Kamino',
  'url': 'https://www.swapi.tech/api/planets/10'},
 {'uid': '11',
  'name': 'Geonosis',
  'url': 'https://www.swapi.tech/api/planets/11'},
 {'uid': '12',
  'name': 'Utapau',
  'url': 'https://www.swapi.tech/api/planets/12'},
 {'uid': '13',
  'name': 'Mustafar',
  'url': 'https://www.swapi.tech/api/planets/13'},
 {'uid': '14',
  'name': 'Kashyyyk',
  'url': 'https://www.swapi.tech/api/planets/14'},
 {'uid': '15',
  'name': 'Polis Massa',
  'url': 'https://www.swapi.tech/api/planets/15'},
 {'uid': '16',
  'name': 'Mygeeto',
  'url': 'https://www.swapi.tech/api/planets/16'},
 {'uid': '17',
  'name': 'Felucia',
  'url': 'https://www.swapi.tech/api/planets/17'},
 {'uid': '18',
  'name': 'Cato Neimoidia',
  'url': 'https://www.swapi.tech/api/planets/18'},
 {'uid': '19',
  'name': 'Saleucami',
  'url': 'https://www.swapi.tech/api/planets/19'},
 {'uid': '20',
  'name': 'Stewjon',
  'url': 'https://www.swapi.tech/api/planets/20'},
 {'uid': '21',
  'name': 'Eriadu',
  'url': 'https://www.swapi.tech/api/planets/21'},
 {'uid': '22',
  'name': 'Corellia',
  'url': 'https://www.swapi.tech/api/planets/22'},
 {'uid': '23',
  'name': 'Rodia',
  'url': 'https://www.swapi.tech/api/planets/23'},
 {'uid': '24',
  'name': 'Nal Hutta',
  'url': 'https://www.swapi.tech/api/planets/24'},
 {'uid': '25',
  'name': 'Dantooine',
  'url': 'https://www.swapi.tech/api/planets/25'},
 {'uid': '26',
  'name': 'Bestine IV',
  'url': 'https://www.swapi.tech/api/planets/26'},
 {'uid': '27',
  'name': 'Ord Mantell',
  'url': 'https://www.swapi.tech/api/planets/27'},
 {'uid': '28',
  'name': 'unknown',
  'url': 'https://www.swapi.tech/api/planets/28'},
 {'uid': '29',
  'name': 'Trandosha',
  'url': 'https://www.swapi.tech/api/planets/29'},
 {'uid': '30',
  'name': 'Socorro',
  'url': 'https://www.swapi.tech/api/planets/30'},
 {'uid': '31',
  'name': 'Mon Cala',
  'url': 'https://www.swapi.tech/api/planets/31'},
 {'uid': '32',
  'name': 'Chandrila',
  'url': 'https://www.swapi.tech/api/planets/32'},
 {'uid': '33',
  'name': 'Sullust',
  'url': 'https://www.swapi.tech/api/planets/33'},
 {'uid': '34',
  'name': 'Toydaria',
  'url': 'https://www.swapi.tech/api/planets/34'},
 {'uid': '35',
  'name': 'Malastare',
  'url': 'https://www.swapi.tech/api/planets/35'},
 {'uid': '36',
  'name': 'Dathomir',
  'url': 'https://www.swapi.tech/api/planets/36'},
 {'uid': '37',
  'name': 'Ryloth',
  'url': 'https://www.swapi.tech/api/planets/37'},
 {'uid': '38',
  'name': 'Aleen Minor',
  'url': 'https://www.swapi.tech/api/planets/38'},
 {'uid': '39',
  'name': 'Vulpter',
  'url': 'https://www.swapi.tech/api/planets/39'},
 {'uid': '40',
  'name': 'Troiken',
  'url': 'https://www.swapi.tech/api/planets/40'},
 {'uid': '41', 'name': 'Tund', 'url': 'https://www.swapi.tech/api/planets/41'},
 {'uid': '42',
  'name': 'Haruun Kal',
  'url': 'https://www.swapi.tech/api/planets/42'},
 {'uid': '43',
  'name': 'Cerea',
  'url': 'https://www.swapi.tech/api/planets/43'},
 {'uid': '44',
  'name': 'Glee Anselm',
  'url': 'https://www.swapi.tech/api/planets/44'},
 {'uid': '45',
  'name': 'Iridonia',
  'url': 'https://www.swapi.tech/api/planets/45'},
 {'uid': '46',
  'name': 'Tholoth',
  'url': 'https://www.swapi.tech/api/planets/46'},
 {'uid': '47',
  'name': 'Iktotch',
  'url': 'https://www.swapi.tech/api/planets/47'},
 {'uid': '48',
  'name': 'Quermia',
  'url': 'https://www.swapi.tech/api/planets/48'},
 {'uid': '49',
  'name': 'Dorin',
  'url': 'https://www.swapi.tech/api/planets/49'},
 {'uid': '50',
  'name': 'Champala',
  'url': 'https://www.swapi.tech/api/planets/50'},
 {'uid': '51',
  'name': 'Mirial',
  'url': 'https://www.swapi.tech/api/planets/51'},
 {'uid': '52',
  'name': 'Serenno',
  'url': 'https://www.swapi.tech/api/planets/52'},
 {'uid': '53',
  'name': 'Concord Dawn',
  'url': 'https://www.swapi.tech/api/planets/53'},
 {'uid': '54',
  'name': 'Zolan',
  'url': 'https://www.swapi.tech/api/planets/54'},
 {'uid': '55', 'name': 'Ojom', 'url': 'https://www.swapi.tech/api/planets/55'},
 {'uid': '56',
  'name': 'Skako',
  'url': 'https://www.swapi.tech/api/planets/56'},
 {'uid': '57',
  'name': 'Muunilinst',
  'url': 'https://www.swapi.tech/api/planets/57'},
 {'uid': '58',
  'name': 'Shili',
  'url': 'https://www.swapi.tech/api/planets/58'},
 {'uid': '59',
  'name': 'Kalee',
  'url': 'https://www.swapi.tech/api/planets/59'},
 {'uid': '60',
  'name': 'Umbara',
  'url': 'https://www.swapi.tech/api/planets/60'}]

In [7]:
df = daft.from_pylist(res)
df.show()

╭──────────┬──────┬────────────────────────────────╮
│ name     ┆ uid  ┆ url                            │
│ ---      ┆ ---  ┆ ---                            │
│ Utf8     ┆ Utf8 ┆ Utf8                           │
╞══════════╪══════╪════════════════════════════════╡
│ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… │
╰──────────┴──────┴────────────────────────────────╯

(Showing first 8 of 60 rows)

In [8]:
@daft.udf(return_dtype=daft.DataType.string())
def get_properties(urls: daft.Series) -> list:
    result = []
    for url in urls.to_pylist():
        json_request = requests.get(url).json()
        result.append(json.dumps(json_request["result"]["properties"]))
    return result

In [9]:
df = df.with_column("properties", get_properties(daft.col("url")))

In [10]:
df.show()

╭──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

In [11]:
options = {
    "catalog": CATALOG,
    "target_schema": "bronze",
}

# 2 Overwrite

In [12]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"


bronze_instance = StarWarsBronze(**options)

In [13]:
# Run one table
bronze_instance.load().transform().write(mode="overwrite").execute("people")

2025-03-15 22:16:44 | people | execute | Started
2025-03-15 22:16:44 | people | load | Started
2025-03-15 22:16:49 | people | load | Completed in 0.07 min
2025-03-15 22:16:49 | people | transform | Started
2025-03-15 22:16:49 | people | transform | Completed in 0.0 min
2025-03-15 22:16:49 | people | write | Started

                                                           d

2025-03-15 22:17:26 | people | write | Completed in 0.62 min
2025-03-15 22:17:26 | people | execute | Completed in 0.7 min

In [14]:
# run multiple tables
bronze_instance.load().transform().write(mode="overwrite").execute("people", "planets")

2025-03-15 22:17:26 | people | execute | Started
2025-03-15 22:17:26 | people | load | Started
2025-03-15 22:17:31 | people | load | Completed in 0.08 min
2025-03-15 22:17:31 | people | transform | Started
2025-03-15 22:17:31 | people | transform | Completed in 0.0 min
2025-03-15 22:17:31 | people | write | Started

                                                           d

2025-03-15 22:18:02 | people | write | Completed in 0.5 min
2025-03-15 22:18:02 | people | execute | Completed in 0.6 min
2025-03-15 22:18:02 | planets | execute | Started
2025-03-15 22:18:02 | planets | load | Started

2025-03-15 22:18:05 | planets | load | Completed in 0.05 min
2025-03-15 22:18:05 | planets | transform | Started
2025-03-15 22:18:05 | planets | transform | Completed in 0.0 min
2025-03-15 22:18:05 | planets | write | Started

                                                           d

2025-03-15 22:18:30 | planets | write | Completed in 0.4 min
2025-03-15 22:18:30 | planets | execute | Completed in 0.45 min

In [15]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:17:31.648835    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 82

In [16]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ LH_BronzeTS                   ┆ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---                           ┆ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Timestamp(Microseconds, None) ┆ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞═══════════════════════════════╪══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ 2025-03-15 22:18:05.615351    ┆ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰───────────────────────────────┴──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

No. Rows: 60

In [17]:
bronze_instance.data["people"].show()

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:17:31.648835    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:17:31.648835    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

In [18]:
bronze_instance.data["planets"].show()

╭───────────────────────────────┬──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ LH_BronzeTS                   ┆ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---                           ┆ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Timestamp(Microseconds, None) ┆ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞═══════════════════════════════╪══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ 2025-03-15 22:18:05.615351    ┆ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:05.615351    ┆ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰───────────────────────────────┴──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

# 3 Replace Where

In [19]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"
    
    def get_replace_condition(self, df: daft.DataFrame, table: str) -> str:
        return "uid > '0'"


bronze_instance = StarWarsBronze(**options)
bronze_instance.load().transform().write(mode="replace").execute("people")

2025-03-15 22:18:36 | people | execute | Started
2025-03-15 22:18:36 | people | load | Started
2025-03-15 22:18:41 | people | load | Completed in 0.07 min
2025-03-15 22:18:41 | people | transform | Started
2025-03-15 22:18:41 | people | transform | Completed in 0.0 min
2025-03-15 22:18:41 | people | write | Started

                                                      d

2025-03-15 22:19:14 | people | write | Completed in 0.53 min

2025-03-15 22:19:14 | people | execute | Completed in 0.62 min

In [20]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:18:41.556405    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:18:41.556405    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 82

# 4 Append

In [21]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"


bronze_instance = StarWarsBronze(**options)
bronze_instance.load().transform().write().execute("people")  # default mode is append

2025-03-15 22:19:14 | people | execute | Started
2025-03-15 22:19:14 | people | load | Started
2025-03-15 22:19:19 | people | load | Completed in 0.07 min
2025-03-15 22:19:19 | people | transform | Started
2025-03-15 22:19:19 | people | transform | Completed in 0.0 min
2025-03-15 22:19:19 | people | write | Started

                                                           d

2025-03-15 22:19:54 | people | write | Completed in 0.57 min
2025-03-15 22:19:54 | people | execute | Completed in 0.65 min

In [22]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:19:19.282962    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:19.282962    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 164

# 5 Merge

In [23]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"
    
    def get_delta_merge_builder(
        self, df: daft.DataFrame, delta_table: DeltaTable
    ) -> TableMerger:
        merge_condition = "target.uid = source.uid"
        builder = delta_table.merge(df, predicate=merge_condition, source_alias="source", target_alias="target")
        builder = builder.when_matched_update_all()
        builder = builder.when_not_matched_insert_all()
        return builder


bronze_instance = StarWarsBronze(**options)
bronze_instance.load().transform().write(mode="merge").execute("people")

2025-03-15 22:19:54 | people | execute | Started
2025-03-15 22:19:54 | people | load | Started
2025-03-15 22:19:59 | people | load | Completed in 0.08 min
2025-03-15 22:19:59 | people | transform | Started
2025-03-15 22:19:59 | people | transform | Completed in 0.0 min
2025-03-15 22:19:59 | people | write | Started

                                                      d

2025-03-15 22:20:33 | people | write | Completed in 0.57 min
2025-03-15 22:20:33 | people | execute | Completed in 0.65 min

In [24]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬──────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name         ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---          ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8         ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪══════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:19:59.723442    ┆ Greedo       ┆ 15   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Nute Gunray  ┆ 33   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Rugor Nass   ┆ 38   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Kit Fisto    ┆ 53   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Leia Organa  ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Sly Moore    ┆ 82   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Palpatine    ┆ 21   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:19:59.723442    ┆ Roos Tarpals ┆ 37   ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆              ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴──────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 164

# 6 Clean Up

In [25]:
import shutil
shutil.rmtree(f"D:/Data/{CATALOG}")