In [ ]:
import requests
from lakehouse.daft import bronze, silver
import json
import daft
from deltalake import DeltaTable

In [5]:
CATALOG = "daft_catalog"

# 1. Set Up and Bronze Data

In [6]:
options = {"catalog": CATALOG, "target_schema": "bronze"}

In [7]:
@daft.udf(return_dtype=daft.DataType.string())
def get_properties(urls: daft.Series) -> list:
    result = []
    for url in urls.to_pylist():
        json_request = requests.get(url).json()
        result.append(json.dumps(json_request["result"]["properties"]))
    return result

In [8]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))

    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"


bronze_instance = StarWarsBronze(**options)

In [9]:
bronze_instance.load().transform().write(mode="overwrite").execute("people", "planets")

2025-03-15 22:25:06 | people | execute | Started
2025-03-15 22:25:06 | people | load | Started
2025-03-15 22:25:11 | people | load | Completed in 0.07 min
2025-03-15 22:25:11 | people | transform | Started
2025-03-15 22:25:11 | people | transform | Completed in 0.0 min
2025-03-15 22:25:11 | people | write | Started
c:\Users\nikol\miniconda3\envs\pyspark3-exec\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                                                           d

2025-03-15 22:25:48 | people | write | Completed in 0.6 min
2025-03-15 22:25:48 | people | execute | Completed in 0.68 min
2025-03-15 22:25:48 | planets | execute | Started
2025-03-15 22:25:48 | planets | load | Started

2025-03-15 22:25:51 | planets | load | Completed in 0.05 min
2025-03-15 22:25:51 | planets | transform | Started
2025-03-15 22:25:51 | planets | transform | Completed in 0.0 min
2025-03-15 22:25:51 | planets | write | Started

                                                           d

2025-03-15 22:26:18 | planets | write | Completed in 0.43 min
2025-03-15 22:26:18 | planets | execute | Completed in 0.5 min

In [10]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:25:11.691737    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:11.691737    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 82

In [11]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ LH_BronzeTS                   ┆ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---                           ┆ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Timestamp(Microseconds, None) ┆ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞═══════════════════════════════╪══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ 2025-03-15 22:25:51.851044    ┆ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:25:51.851044    ┆ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰───────────────────────────────┴──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

No. Rows: 60

In [12]:
options = {
    "catalog": CATALOG,
    "source_schema": "bronze",
    "target_schema": "silver",
}

# 2 Overwrite

In [13]:
config = {
    "load": {
        "mode": "default",
        "filter": "all",
        "date_col": "LH_BronzeTS",
    },
    "transform": {
        "ignore_defaults": False,
        "transformation_order": [
            "add_dummy_col",
            "rename_columns",
            "tbl_transformations",
            "select_columns",
            "cast_column_types",
        ],
        # "tbl_transformations": {"tbl": "custom_transform1"},
        "rename_columns": {
            "planets": {"dummy_col": "dummy"},
            "people": {"dummy_col": "dummy"},
        },
        "select_columns": {
            "planets": ["LH_BronzeTS", "name", "uid", "url", "dummy"],
            "people": ["LH_BronzeTS", "name", "uid", "url", "dummy"],
        },
        "cast_column_types": {
            "planets": {"dummy": "string", "id": "int"},
            "people": {"dummy": "string", "id": "int"},
        },
    },
    "write": {
        "mode": "overwrite",
        "overwrite_schema": True,
    },
}

In [ ]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast("int"))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"

    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"

    def add_dummy_col(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("dummy_col", daft.lit("dummy"))


silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver", config=config
)

In [15]:
silver_instance.execute("people", "planets")

2025-03-15 22:26:18 | people | execute | Started
2025-03-15 22:26:18 | people | load | Started
2025-03-15 22:26:18 | people | load | Completed in 0.0 min
2025-03-15 22:26:18 | people | transform | Started
2025-03-15 22:26:18 | people | transform | Completed in 0.0 min
2025-03-15 22:26:18 | people | write | Started
2025-03-15 22:26:18 | people | write | Completed in 0.0 min
2025-03-15 22:26:18 | people | execute | Completed in 0.0 min
2025-03-15 22:26:18 | planets | execute | Started
2025-03-15 22:26:18 | planets | load | Started
2025-03-15 22:26:18 | planets | load | Completed in 0.0 min
2025-03-15 22:26:18 | planets | transform | Started
2025-03-15 22:26:18 | planets | transform | Completed in 0.0 min
2025-03-15 22:26:18 | planets | write | Started
2025-03-15 22:26:18 | planets | write | Completed in 0.0 min
2025-03-15 22:26:18 | planets | execute | Completed in 0.0 min

In [16]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────┬──────────────────────────┬────────────────────┬───────┬──────────────────────────┬───────╮
│ LH_SilverTS               ┆ LH_BronzeTS              ┆ name               ┆ uid   ┆ url                      ┆ dummy │
│ ---                       ┆ ---                      ┆ ---                ┆ ---   ┆ ---                      ┆ ---   │
│ Timestamp(Microseconds,   ┆ Timestamp(Microseconds,  ┆ Utf8               ┆ Int32 ┆ Utf8                     ┆ Utf8  │
│ None)                     ┆ None)                    ┆                    ┆       ┆                          ┆       │
╞═══════════════════════════╪══════════════════════════╪════════════════════╪═══════╪══════════════════════════╪═══════╡
│ 2025-03-15                ┆ 2025-03-15               ┆ Luke Skywalker     ┆ 1     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ C-3PO              ┆ 2     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ R2-D2              ┆ 3     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ Darth Vader        ┆ 4     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ Leia Organa        ┆ 5     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ Owen Lars          ┆ 6     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ Beru Whitesun lars ┆ 7     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15               ┆ R5-D4              ┆ 8     ┆ https://www.swapi.tech/a ┆ dummy │
│ 22:26:18.625950           ┆ 22:25:11.691737          ┆                    ┆       ┆ pi/pe…                   ┆       │
╰───────────────────────────┴──────────────────────────┴────────────────────┴───────┴──────────────────────────┴───────╯

(Showing first 8 rows)

No. Rows: 82

In [17]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────────────┬──────────────────────────────┬──────────┬───────┬─────────────────────────────┬───────╮
│ LH_SilverTS                  ┆ LH_BronzeTS                  ┆ name     ┆ uid   ┆ url                         ┆ dummy │
│ ---                          ┆ ---                          ┆ ---      ┆ ---   ┆ ---                         ┆ ---   │
│ Timestamp(Microseconds,      ┆ Timestamp(Microseconds,      ┆ Utf8     ┆ Int32 ┆ Utf8                        ┆ Utf8  │
│ None)                        ┆ None)                        ┆          ┆       ┆                             ┆       │
╞══════════════════════════════╪══════════════════════════════╪══════════╪═══════╪═════════════════════════════╪═══════╡
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Tatooine ┆ 1     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Alderaan ┆ 2     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Yavin IV ┆ 3     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Hoth     ┆ 4     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Dagobah  ┆ 5     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Bespin   ┆ 6     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Endor    ┆ 7     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 22:26:18.676767   ┆ 2025-03-15 22:25:51.851044   ┆ Naboo    ┆ 8     ┆ https://www.swapi.tech/api/ ┆ dummy │
│                              ┆                              ┆          ┆       ┆ pl…                         ┆       │
╰──────────────────────────────┴──────────────────────────────┴──────────┴───────┴─────────────────────────────┴───────╯

(Showing first 8 rows)

No. Rows: 60

In [18]:
dt = DeltaTable(f"D:/Data/{CATALOG}/silver/planets")
daft.from_pylist(dt.history()).show()

╭────────────────────┬──────────────┬────────────────────────────────────────────────────┬───────────────┬─────────╮
│ clientVersion      ┆ operation    ┆ operationParameters                                ┆ timestamp     ┆ version │
│ ---                ┆ ---          ┆ ---                                                ┆ ---           ┆ ---     │
│ Utf8               ┆ Utf8         ┆ Struct[location: Utf8, metadata: Utf8, mode: Utf8, ┆ Int64         ┆ Int64   │
│                    ┆              ┆ protocol: Utf8]                                    ┆               ┆         │
╞════════════════════╪══════════════╪════════════════════════════════════════════════════╪═══════════════╪═════════╡
│ delta-rs.py-0.25.4 ┆ CREATE TABLE ┆ {location: file:///D:/Data/da…                     ┆ 1742073978698 ┆ 0       │
╰────────────────────┴──────────────┴────────────────────────────────────────────────────┴───────────────┴─────────╯

(Showing first 1 of 1 rows)

# 6 Clean Up

In [19]:
import shutil

shutil.rmtree(f"D:/Data/{CATALOG}")