In [4]:
import requests
from lakehouse.daft import bronze, silver
from lakehouse.daft.utils import daftutils
import json
import daft
from deltalake.table import TableMerger, DeltaTable

In [5]:
CATALOG = "daft_catalog"

# 1. Set Up and Bronze Data

In [6]:
options = {"catalog": CATALOG, "target_schema": "bronze"}

In [7]:
@daft.udf(return_dtype=daft.DataType.string())
def get_properties(urls: daft.Series) -> list:
    result = []
    for url in urls.to_pylist():
        json_request = requests.get(url).json()
        result.append(json.dumps(json_request["result"]["properties"]))
    return result

In [8]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"


bronze_instance = StarWarsBronze(**options)

In [9]:
bronze_instance.load().transform().write(mode="overwrite").execute("people", "planets")

2025-03-15 22:47:02 | people | execute | Started
2025-03-15 22:47:02 | people | load | Started
2025-03-15 22:47:07 | people | load | Completed in 0.07 min
2025-03-15 22:47:07 | people | transform | Started
2025-03-15 22:47:07 | people | transform | Completed in 0.0 min
2025-03-15 22:47:07 | people | write | Started
c:\Users\nikol\miniconda3\envs\pyspark3-exec\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                                                           d

2025-03-15 22:47:41 | people | write | Completed in 0.57 min
2025-03-15 22:47:41 | people | execute | Completed in 0.63 min
2025-03-15 22:47:41 | planets | execute | Started
2025-03-15 22:47:41 | planets | load | Started

2025-03-15 22:47:44 | planets | load | Completed in 0.05 min
2025-03-15 22:47:44 | planets | transform | Started
2025-03-15 22:47:44 | planets | transform | Completed in 0.0 min
2025-03-15 22:47:44 | planets | write | Started

                                                           d

2025-03-15 22:48:08 | planets | write | Completed in 0.38 min
2025-03-15 22:48:08 | planets | execute | Completed in 0.43 min

In [10]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 22:47:07.220900    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:07.220900    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 82

In [11]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ LH_BronzeTS                   ┆ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---                           ┆ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Timestamp(Microseconds, None) ┆ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞═══════════════════════════════╪══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ 2025-03-15 22:47:44.286978    ┆ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 22:47:44.286978    ┆ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰───────────────────────────────┴──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

No. Rows: 60

In [12]:
options = {
    "catalog": CATALOG,
    "source_schema": "bronze",
    "target_schema": "silver",
}

# 2 Overwrite

In [13]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast(daftutils.get_daft_dtype("int")))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"

silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver"
)

In [14]:
silver_instance.load(filter="custom").transform().write(mode="overwrite").execute(
    "people", "planets"
)

2025-03-15 22:48:08 | people | execute | Started
2025-03-15 22:48:08 | people | load | Started
2025-03-15 22:48:08 | people | load | Completed in 0.0 min
2025-03-15 22:48:08 | people | transform | Started
2025-03-15 22:48:08 | people | transform | Completed in 0.0 min
2025-03-15 22:48:08 | people | write | Started
2025-03-15 22:48:08 | people | write | Completed in 0.0 min
2025-03-15 22:48:08 | people | execute | Completed in 0.0 min
2025-03-15 22:48:08 | planets | execute | Started
2025-03-15 22:48:08 | planets | load | Started
2025-03-15 22:48:08 | planets | load | Completed in 0.0 min
2025-03-15 22:48:08 | planets | transform | Started
2025-03-15 22:48:08 | planets | transform | Completed in 0.0 min
2025-03-15 22:48:08 | planets | write | Started
2025-03-15 22:48:08 | planets | write | Completed in 0.0 min
2025-03-15 22:48:08 | planets | execute | Completed in 0.0 min

In [15]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────┬──────────────────────┬──────────────────┬───────┬──────────────────────┬──────────────────────╮
│ LH_SilverTS          ┆ LH_BronzeTS          ┆ name             ┆ uid   ┆ url                  ┆ properties           │
│ ---                  ┆ ---                  ┆ ---              ┆ ---   ┆ ---                  ┆ ---                  │
│ Timestamp(Microsecon ┆ Timestamp(Microsecon ┆ Utf8             ┆ Int32 ┆ Utf8                 ┆ Utf8                 │
│ ds, None)            ┆ ds, None)            ┆                  ┆       ┆                      ┆                      │
╞══════════════════════╪══════════════════════╪══════════════════╪═══════╪══════════════════════╪══════════════════════╡
│ 2025-03-15           ┆ 2025-03-15           ┆ Luke Skywalker   ┆ 1     ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ C-3PO            ┆ 2     ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Obi-Wan Kenobi   ┆ 10    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Anakin Skywalker ┆ 11    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Wilhuff Tarkin   ┆ 12    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Chewbacca        ┆ 13    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Han Solo         ┆ 14    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Greedo           ┆ 15    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:08.322093      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
╰──────────────────────┴──────────────────────┴──────────────────┴───────┴──────────────────────┴──────────────────────╯

(Showing first 8 rows)

No. Rows: 17

In [16]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭─────────────────────────┬────────────────────────┬─────────────┬───────┬────────────────────────┬────────────────────╮
│ LH_SilverTS             ┆ LH_BronzeTS            ┆ name        ┆ uid   ┆ url                    ┆ properties         │
│ ---                     ┆ ---                    ┆ ---         ┆ ---   ┆ ---                    ┆ ---                │
│ Timestamp(Microseconds, ┆ Timestamp(Microseconds ┆ Utf8        ┆ Int32 ┆ Utf8                   ┆ Utf8               │
│ None)                   ┆ , None)                ┆             ┆       ┆                        ┆                    │
╞═════════════════════════╪════════════════════════╪═════════════╪═══════╪════════════════════════╪════════════════════╡
│ 2025-03-15              ┆ 2025-03-15             ┆ Tatooine    ┆ 1     ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Alderaan    ┆ 2     ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Kamino      ┆ 10    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Geonosis    ┆ 11    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Utapau      ┆ 12    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Mustafar    ┆ 13    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Kashyyyk    ┆ 14    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Polis Massa ┆ 15    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:08.380619         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
╰─────────────────────────┴────────────────────────┴─────────────┴───────┴────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 18

In [17]:
# without load filter
silver_instance.load().transform().write(mode="overwrite").execute("people", "planets")

2025-03-15 22:48:08 | people | execute | Started
2025-03-15 22:48:08 | people | load | Started
2025-03-15 22:48:08 | people | load | Completed in 0.0 min
2025-03-15 22:48:08 | people | transform | Started
2025-03-15 22:48:08 | people | transform | Completed in 0.0 min
2025-03-15 22:48:08 | people | write | Started
2025-03-15 22:48:08 | people | write | Completed in 0.0 min
2025-03-15 22:48:08 | people | execute | Completed in 0.0 min
2025-03-15 22:48:08 | planets | execute | Started
2025-03-15 22:48:08 | planets | load | Started
2025-03-15 22:48:08 | planets | load | Completed in 0.0 min
2025-03-15 22:48:08 | planets | transform | Started
2025-03-15 22:48:08 | planets | transform | Completed in 0.0 min
2025-03-15 22:48:08 | planets | write | Started
2025-03-15 22:48:09 | planets | write | Completed in 0.02 min
2025-03-15 22:48:09 | planets | execute | Completed in 0.02 min

In [18]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────┬──────────────────────┬────────────────────┬───────┬─────────────────────┬─────────────────────╮
│ LH_SilverTS          ┆ LH_BronzeTS          ┆ name               ┆ uid   ┆ url                 ┆ properties          │
│ ---                  ┆ ---                  ┆ ---                ┆ ---   ┆ ---                 ┆ ---                 │
│ Timestamp(Microsecon ┆ Timestamp(Microsecon ┆ Utf8               ┆ Int32 ┆ Utf8                ┆ Utf8                │
│ ds, None)            ┆ ds, None)            ┆                    ┆       ┆                     ┆                     │
╞══════════════════════╪══════════════════════╪════════════════════╪═══════╪═════════════════════╪═════════════════════╡
│ 2025-03-15           ┆ 2025-03-15           ┆ Luke Skywalker     ┆ 1     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ C-3PO              ┆ 2     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ R2-D2              ┆ 3     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Darth Vader        ┆ 4     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Leia Organa        ┆ 5     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Owen Lars          ┆ 6     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Beru Whitesun lars ┆ 7     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ R5-D4              ┆ 8     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:08.490892      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
╰──────────────────────┴──────────────────────┴────────────────────┴───────┴─────────────────────┴─────────────────────╯

(Showing first 8 rows)

No. Rows: 82

In [19]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────────┬─────────────────────────┬──────────┬───────┬─────────────────────────┬────────────────────╮
│ LH_SilverTS              ┆ LH_BronzeTS             ┆ name     ┆ uid   ┆ url                     ┆ properties         │
│ ---                      ┆ ---                     ┆ ---      ┆ ---   ┆ ---                     ┆ ---                │
│ Timestamp(Microseconds,  ┆ Timestamp(Microseconds, ┆ Utf8     ┆ Int32 ┆ Utf8                    ┆ Utf8               │
│ None)                    ┆ None)                   ┆          ┆       ┆                         ┆                    │
╞══════════════════════════╪═════════════════════════╪══════════╪═══════╪═════════════════════════╪════════════════════╡
│ 2025-03-15               ┆ 2025-03-15              ┆ Tatooine ┆ 1     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Alderaan ┆ 2     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Yavin IV ┆ 3     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Hoth     ┆ 4     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Dagobah  ┆ 5     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Bespin   ┆ 6     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Endor    ┆ 7     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15               ┆ 2025-03-15              ┆ Naboo    ┆ 8     ┆ https://www.swapi.tech/ ┆ {"created":        │
│ 22:48:08.562241          ┆ 22:47:44.286978         ┆          ┆       ┆ api/pl…                 ┆ "2025-03-15T00:00… │
╰──────────────────────────┴─────────────────────────┴──────────┴───────┴─────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 60

# 3 Replace Where

In [20]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast(daftutils.get_daft_dtype("int")))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"
    
    def get_replace_condition(self, df: daft.DataFrame, table: str) -> str:
        return "uid > 0"

silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver"
)

silver_instance.load(filter="custom").transform().write(mode="replace").execute(
    "people", "planets"
)

2025-03-15 22:48:09 | people | execute | Started
2025-03-15 22:48:09 | people | load | Started
2025-03-15 22:48:09 | people | load | Completed in 0.0 min
2025-03-15 22:48:09 | people | transform | Started
2025-03-15 22:48:09 | people | transform | Completed in 0.0 min
2025-03-15 22:48:09 | people | write | Started
2025-03-15 22:48:10 | people | write | Completed in 0.0 min
2025-03-15 22:48:10 | people | execute | Completed in 0.0 min
2025-03-15 22:48:10 | planets | execute | Started
2025-03-15 22:48:10 | planets | load | Started
2025-03-15 22:48:10 | planets | load | Completed in 0.0 min
2025-03-15 22:48:10 | planets | transform | Started
2025-03-15 22:48:10 | planets | transform | Completed in 0.0 min
2025-03-15 22:48:10 | planets | write | Started
2025-03-15 22:48:10 | planets | write | Completed in 0.0 min
2025-03-15 22:48:10 | planets | execute | Completed in 0.0 min

In [21]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────┬──────────────────────┬──────────────────┬───────┬──────────────────────┬──────────────────────╮
│ LH_SilverTS          ┆ LH_BronzeTS          ┆ name             ┆ uid   ┆ url                  ┆ properties           │
│ ---                  ┆ ---                  ┆ ---              ┆ ---   ┆ ---                  ┆ ---                  │
│ Timestamp(Microsecon ┆ Timestamp(Microsecon ┆ Utf8             ┆ Int32 ┆ Utf8                 ┆ Utf8                 │
│ ds, None)            ┆ ds, None)            ┆                  ┆       ┆                      ┆                      │
╞══════════════════════╪══════════════════════╪══════════════════╪═══════╪══════════════════════╪══════════════════════╡
│ 2025-03-15           ┆ 2025-03-15           ┆ Luke Skywalker   ┆ 1     ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ C-3PO            ┆ 2     ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Obi-Wan Kenobi   ┆ 10    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Anakin Skywalker ┆ 11    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Wilhuff Tarkin   ┆ 12    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Chewbacca        ┆ 13    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Han Solo         ┆ 14    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Greedo           ┆ 15    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:09.876354      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
╰──────────────────────┴──────────────────────┴──────────────────┴───────┴──────────────────────┴──────────────────────╯

(Showing first 8 rows)

No. Rows: 17

# 4 Append

In [22]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast(daftutils.get_daft_dtype("int")))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"

silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver"
)
silver_instance.load().transform().write().execute(
    "people", "planets"
)  # default mode is append

2025-03-15 22:48:10 | people | execute | Started
2025-03-15 22:48:10 | people | load | Started
2025-03-15 22:48:10 | people | load | Completed in 0.0 min
2025-03-15 22:48:10 | people | transform | Started
2025-03-15 22:48:10 | people | transform | Completed in 0.0 min
2025-03-15 22:48:10 | people | write | Started
2025-03-15 22:48:10 | people | write | Completed in 0.0 min
2025-03-15 22:48:10 | people | execute | Completed in 0.0 min
2025-03-15 22:48:10 | planets | execute | Started
2025-03-15 22:48:10 | planets | load | Started
2025-03-15 22:48:10 | planets | load | Completed in 0.0 min
2025-03-15 22:48:10 | planets | transform | Started
2025-03-15 22:48:10 | planets | transform | Completed in 0.0 min
2025-03-15 22:48:10 | planets | write | Started
2025-03-15 22:48:10 | planets | write | Completed in 0.0 min
2025-03-15 22:48:10 | planets | execute | Completed in 0.0 min

In [23]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────┬──────────────────────┬────────────────────┬───────┬─────────────────────┬─────────────────────╮
│ LH_SilverTS          ┆ LH_BronzeTS          ┆ name               ┆ uid   ┆ url                 ┆ properties          │
│ ---                  ┆ ---                  ┆ ---                ┆ ---   ┆ ---                 ┆ ---                 │
│ Timestamp(Microsecon ┆ Timestamp(Microsecon ┆ Utf8               ┆ Int32 ┆ Utf8                ┆ Utf8                │
│ ds, None)            ┆ ds, None)            ┆                    ┆       ┆                     ┆                     │
╞══════════════════════╪══════════════════════╪════════════════════╪═══════╪═════════════════════╪═════════════════════╡
│ 2025-03-15           ┆ 2025-03-15           ┆ Luke Skywalker     ┆ 1     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ C-3PO              ┆ 2     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ R2-D2              ┆ 3     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Darth Vader        ┆ 4     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Leia Organa        ┆ 5     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Owen Lars          ┆ 6     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Beru Whitesun lars ┆ 7     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ R5-D4              ┆ 8     ┆ https://www.swapi.t ┆ {"created":         │
│ 22:48:10.118569      ┆ 22:47:07.220900      ┆                    ┆       ┆ ech/api/pe…         ┆ "2025-03-15T00:00…  │
╰──────────────────────┴──────────────────────┴────────────────────┴───────┴─────────────────────┴─────────────────────╯

(Showing first 8 rows)

No. Rows: 99

# 5 Merge

In [24]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast(daftutils.get_daft_dtype("int")))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"

    def get_delta_merge_builder(
        self, df: daft.DataFrame, delta_table: DeltaTable
    ) -> TableMerger:
        merge_condition = "target.url = source.url"
        builder = delta_table.merge(df, predicate=merge_condition, source_alias="source", target_alias="target")
        builder = builder.when_matched_update_all()
        builder = builder.when_not_matched_insert_all()
        return builder

silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver"
)

silver_instance.load().transform().write(mode="merge").execute("people", "planets")

2025-03-15 22:48:10 | people | execute | Started
2025-03-15 22:48:10 | people | load | Started
2025-03-15 22:48:10 | people | load | Completed in 0.0 min
2025-03-15 22:48:10 | people | transform | Started
2025-03-15 22:48:10 | people | transform | Completed in 0.0 min
2025-03-15 22:48:10 | people | write | Started
2025-03-15 22:48:11 | people | write | Completed in 0.02 min
2025-03-15 22:48:11 | people | execute | Completed in 0.02 min
2025-03-15 22:48:11 | planets | execute | Started
2025-03-15 22:48:11 | planets | load | Started
2025-03-15 22:48:11 | planets | load | Completed in 0.0 min
2025-03-15 22:48:11 | planets | transform | Started
2025-03-15 22:48:11 | planets | transform | Completed in 0.0 min
2025-03-15 22:48:11 | planets | write | Started
2025-03-15 22:48:11 | planets | write | Completed in 0.0 min
2025-03-15 22:48:11 | planets | execute | Completed in 0.0 min

In [25]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭──────────────────────┬──────────────────────┬──────────────────┬───────┬──────────────────────┬──────────────────────╮
│ LH_SilverTS          ┆ LH_BronzeTS          ┆ name             ┆ uid   ┆ url                  ┆ properties           │
│ ---                  ┆ ---                  ┆ ---              ┆ ---   ┆ ---                  ┆ ---                  │
│ Timestamp(Microsecon ┆ Timestamp(Microsecon ┆ Utf8             ┆ Int32 ┆ Utf8                 ┆ Utf8                 │
│ ds, None)            ┆ ds, None)            ┆                  ┆       ┆                      ┆                      │
╞══════════════════════╪══════════════════════╪══════════════════╪═══════╪══════════════════════╪══════════════════════╡
│ 2025-03-15           ┆ 2025-03-15           ┆ Obi-Wan Kenobi   ┆ 10    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Anakin Skywalker ┆ 11    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Boba Fett        ┆ 22    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Lando Calrissian ┆ 25    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Luke Skywalker   ┆ 1     ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Jek Tono Porkins ┆ 19    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Wilhuff Tarkin   ┆ 12    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15           ┆ 2025-03-15           ┆ Greedo           ┆ 15    ┆ https://www.swapi.te ┆ {"created":          │
│ 22:48:10.279821      ┆ 22:47:07.220900      ┆                  ┆       ┆ ch/api/pe…           ┆ "2025-03-15T00:00…   │
╰──────────────────────┴──────────────────────┴──────────────────┴───────┴──────────────────────┴──────────────────────╯

(Showing first 8 rows)

No. Rows: 99

In [26]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭─────────────────────────┬────────────────────────┬─────────────┬───────┬────────────────────────┬────────────────────╮
│ LH_SilverTS             ┆ LH_BronzeTS            ┆ name        ┆ uid   ┆ url                    ┆ properties         │
│ ---                     ┆ ---                    ┆ ---         ┆ ---   ┆ ---                    ┆ ---                │
│ Timestamp(Microseconds, ┆ Timestamp(Microseconds ┆ Utf8        ┆ Int32 ┆ Utf8                   ┆ Utf8               │
│ None)                   ┆ , None)                ┆             ┆       ┆                        ┆                    │
╞═════════════════════════╪════════════════════════╪═════════════╪═══════╪════════════════════════╪════════════════════╡
│ 2025-03-15              ┆ 2025-03-15             ┆ Ryloth      ┆ 37    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Trandosha   ┆ 29    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Tatooine    ┆ 1     ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Glee Anselm ┆ 44    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Umbara      ┆ 60    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Vulpter     ┆ 39    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Mon Cala    ┆ 31    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15              ┆ 2025-03-15             ┆ Chandrila   ┆ 32    ┆ https://www.swapi.tech ┆ {"created":        │
│ 22:48:11.471530         ┆ 22:47:44.286978        ┆             ┆       ┆ /api/pl…               ┆ "2025-03-15T00:00… │
╰─────────────────────────┴────────────────────────┴─────────────┴───────┴────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 78

# 6 Clean Up

In [27]:
import shutil
shutil.rmtree(f"D:/Data/{CATALOG}")