In [4]:
import requests
from lakehouse.daft import bronze, silver
from lakehouse.daft.utils import daftutils
import json
import daft

In [5]:
CATALOG = "daft_catalog"

# 1. Set Up and Bronze Data

In [6]:
options = {"catalog": CATALOG, "target_schema": "bronze"}

In [7]:
@daft.udf(return_dtype=daft.DataType.string())
def get_properties(urls: daft.Series) -> list:
    result = []
    for url in urls.to_pylist():
        json_request = requests.get(url).json()
        result.append(json.dumps(json_request["result"]["properties"]))
    return result

In [8]:
class StarWarsBronze(bronze.Bronze):
    def custom_load(self, table):
        results = []
        query = f"https://swapi.tech/api/{table}"
        json_request = requests.get(query).json()
        results.extend(json_request["results"])

        while json_request["next"]:
            json_request = requests.get(json_request["next"]).json()
            results.extend(json_request["results"])
        return daft.from_pylist(results)

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("properties", get_properties(daft.col("url")))
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"


bronze_instance = StarWarsBronze(**options)

In [9]:
bronze_instance.load().transform().write(mode="overwrite").execute("people", "planets")

2025-03-15 23:00:40 | people | execute | Started
2025-03-15 23:00:40 | people | load | Started
2025-03-15 23:00:45 | people | load | Completed in 0.07 min
2025-03-15 23:00:45 | people | transform | Started
2025-03-15 23:00:45 | people | transform | Completed in 0.0 min
2025-03-15 23:00:45 | people | write | Started
c:\Users\nikol\miniconda3\envs\pyspark3-exec\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                                                           d

2025-03-15 23:01:18 | people | write | Completed in 0.55 min
2025-03-15 23:01:18 | people | execute | Completed in 0.63 min
2025-03-15 23:01:18 | planets | execute | Started
2025-03-15 23:01:18 | planets | load | Started

2025-03-15 23:01:21 | planets | load | Completed in 0.05 min
2025-03-15 23:01:21 | planets | transform | Started
2025-03-15 23:01:21 | planets | transform | Completed in 0.0 min
2025-03-15 23:01:21 | planets | write | Started

                                                           d

2025-03-15 23:01:44 | planets | write | Completed in 0.37 min
2025-03-15 23:01:44 | planets | execute | Completed in 0.42 min

In [10]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬────────────────────┬──────┬────────────────────────────────┬────────────────────╮
│ LH_BronzeTS                   ┆ name               ┆ uid  ┆ url                            ┆ properties         │
│ ---                           ┆ ---                ┆ ---  ┆ ---                            ┆ ---                │
│ Timestamp(Microseconds, None) ┆ Utf8               ┆ Utf8 ┆ Utf8                           ┆ Utf8               │
╞═══════════════════════════════╪════════════════════╪══════╪════════════════════════════════╪════════════════════╡
│ 2025-03-15 23:00:45.639024    ┆ Luke Skywalker     ┆ 1    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ C-3PO              ┆ 2    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ R2-D2              ┆ 3    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ Darth Vader        ┆ 4    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ Leia Organa        ┆ 5    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ Owen Lars          ┆ 6    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ Beru Whitesun lars ┆ 7    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:00:45.639024    ┆ R5-D4              ┆ 8    ┆ https://www.swapi.tech/api/pe… ┆ {"created":        │
│                               ┆                    ┆      ┆                                ┆ "2025-03-15T00:00… │
╰───────────────────────────────┴────────────────────┴──────┴────────────────────────────────┴────────────────────╯

(Showing first 8 rows)

No. Rows: 82

In [11]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/bronze/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────────┬──────────┬──────┬────────────────────────────────┬────────────────────────────────╮
│ LH_BronzeTS                   ┆ name     ┆ uid  ┆ url                            ┆ properties                     │
│ ---                           ┆ ---      ┆ ---  ┆ ---                            ┆ ---                            │
│ Timestamp(Microseconds, None) ┆ Utf8     ┆ Utf8 ┆ Utf8                           ┆ Utf8                           │
╞═══════════════════════════════╪══════════╪══════╪════════════════════════════════╪════════════════════════════════╡
│ 2025-03-15 23:01:21.988149    ┆ Tatooine ┆ 1    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Alderaan ┆ 2    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Yavin IV ┆ 3    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Hoth     ┆ 4    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Dagobah  ┆ 5    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Bespin   ┆ 6    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Endor    ┆ 7    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:21.988149    ┆ Naboo    ┆ 8    ┆ https://www.swapi.tech/api/pl… ┆ {"created": "2025-03-15T00:00… │
╰───────────────────────────────┴──────────┴──────┴────────────────────────────────┴────────────────────────────────╯

(Showing first 8 rows)

No. Rows: 60

In [12]:
options = {
    "catalog": CATALOG,
    "source_schema": "bronze",
    "target_schema": "silver",
}

# 2 Overwrite

In [13]:
class StarWarsSilver(silver.Silver):
    def custom_filter(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.where("uid <= '25'")

    def custom_transform(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        df = df.with_column("uid", daft.col("uid").cast(daftutils.get_daft_dtype("int")))
        return df

    def source_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.source_schema}/{table}"
    
    def target_path(self, table: str) -> str:
        return f"D:/Data/{self.catalog}/{self.target_schema}/{table}"

    def add_dummy_col(self, df: daft.DataFrame, table: str) -> daft.DataFrame:
        return df.with_column("dummy_col", daft.lit("dummy"))

silver_instance = StarWarsSilver(
    catalog=CATALOG, source_schema="bronze", target_schema="silver"
)

In [14]:
silver_instance = silver_instance.load(filter="custom")
silver_instance.transform(
    transformation_order=[
        "add_dummy_col",
        "rename_columns",
        "tbl_transformations",
        "select_columns",
        "cast_column_types",
    ],
    rename_columns={
        "planets": {"dummy_col": "dummy"},
        "people": {"dummy_col": "dummy"},
    },
    select_columns={
        "planets": ["LH_BronzeTS", "name", "uid", "url", "dummy"],
        "people": ["LH_BronzeTS", "name", "uid", "url", "dummy"],
    },
    cast_column_types={
        "planets": {"dummy": "string", "id": "int"},
        "people": {"dummy": "string", "id": "int"},
    },
)
silver_instance.write(mode="overwrite").execute("people", "planets")

2025-03-15 23:01:44 | people | execute | Started
2025-03-15 23:01:44 | people | load | Started
2025-03-15 23:01:44 | people | load | Completed in 0.0 min
2025-03-15 23:01:44 | people | transform | Started
2025-03-15 23:01:44 | people | transform | Completed in 0.0 min
2025-03-15 23:01:44 | people | write | Started
2025-03-15 23:01:44 | people | write | Completed in 0.0 min
2025-03-15 23:01:44 | people | execute | Completed in 0.0 min
2025-03-15 23:01:44 | planets | execute | Started
2025-03-15 23:01:44 | planets | load | Started
2025-03-15 23:01:44 | planets | load | Completed in 0.0 min
2025-03-15 23:01:44 | planets | transform | Started
2025-03-15 23:01:44 | planets | transform | Completed in 0.0 min
2025-03-15 23:01:44 | planets | write | Started
2025-03-15 23:01:45 | planets | write | Completed in 0.0 min
2025-03-15 23:01:45 | planets | execute | Completed in 0.0 min

In [15]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/people")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭───────────────────────────┬───────────────────────────┬──────────────────┬───────┬───────────────────────────┬───────╮
│ LH_SilverTS               ┆ LH_BronzeTS               ┆ name             ┆ uid   ┆ url                       ┆ dummy │
│ ---                       ┆ ---                       ┆ ---              ┆ ---   ┆ ---                       ┆ ---   │
│ Timestamp(Microseconds,   ┆ Timestamp(Microseconds,   ┆ Utf8             ┆ Int32 ┆ Utf8                      ┆ Utf8  │
│ None)                     ┆ None)                     ┆                  ┆       ┆                           ┆       │
╞═══════════════════════════╪═══════════════════════════╪══════════════════╪═══════╪═══════════════════════════╪═══════╡
│ 2025-03-15                ┆ 2025-03-15                ┆ Luke Skywalker   ┆ 1     ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ C-3PO            ┆ 2     ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Obi-Wan Kenobi   ┆ 10    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Anakin Skywalker ┆ 11    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Wilhuff Tarkin   ┆ 12    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Chewbacca        ┆ 13    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Han Solo         ┆ 14    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15                ┆ 2025-03-15                ┆ Greedo           ┆ 15    ┆ https://www.swapi.tech/ap ┆ dummy │
│ 23:01:44.909465           ┆ 23:00:45.639024           ┆                  ┆       ┆ i/pe…                     ┆       │
╰───────────────────────────┴───────────────────────────┴──────────────────┴───────┴───────────────────────────┴───────╯

(Showing first 8 rows)

No. Rows: 17

In [16]:
df = daft.read_deltalake(f"D:/Data/{CATALOG}/silver/planets")
df.show()
print(f"No. Rows: {df.count_rows()}")

╭─────────────────────────────┬─────────────────────────────┬─────────────┬───────┬────────────────────────────┬───────╮
│ LH_SilverTS                 ┆ LH_BronzeTS                 ┆ name        ┆ uid   ┆ url                        ┆ dummy │
│ ---                         ┆ ---                         ┆ ---         ┆ ---   ┆ ---                        ┆ ---   │
│ Timestamp(Microseconds,     ┆ Timestamp(Microseconds,     ┆ Utf8        ┆ Int32 ┆ Utf8                       ┆ Utf8  │
│ None)                       ┆ None)                       ┆             ┆       ┆                            ┆       │
╞═════════════════════════════╪═════════════════════════════╪═════════════╪═══════╪════════════════════════════╪═══════╡
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Tatooine    ┆ 1     ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Alderaan    ┆ 2     ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Kamino      ┆ 10    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Geonosis    ┆ 11    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Utapau      ┆ 12    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Mustafar    ┆ 13    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Kashyyyk    ┆ 14    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 2025-03-15 23:01:44.969404  ┆ 2025-03-15 23:01:21.988149  ┆ Polis Massa ┆ 15    ┆ https://www.swapi.tech/api ┆ dummy │
│                             ┆                             ┆             ┆       ┆ /pl…                       ┆       │
╰─────────────────────────────┴─────────────────────────────┴─────────────┴───────┴────────────────────────────┴───────╯

(Showing first 8 rows)

No. Rows: 18

# 6 Clean Up

In [17]:
import shutil
shutil.rmtree(f"D:/Data/{CATALOG}")